const careOriginalRender=renderCustomerCareSection;
const careOriginalCollect=collectCustomerCareSettings;
collectCustomerCareSettings=function(form){
 const settings=careOriginalCollect(form);
 const preferences={...(workspace.customer_care_settings.dashboard_preferences||{})};
 form.querySelectorAll('[data-care-setting]').forEach(input=>{preferences[input.dataset.careSetting]=input.type==='checkbox'?input.checked:input.type==='number'?Number(input.value):input.value;});
 preferences.working_days=Array.from(form.querySelectorAll('[data-care-day]:checked')).map(input=>input.value);
 settings.dashboard_preferences=preferences;
 const tracking=form.querySelector('[data-care-setting="order_tracking"]');
 if(tracking)settings.order_tracking_enabled=tracking.checked;
 const handoff=form.querySelector('[data-care-setting="explicit_agent"]');
 if(handoff)settings.human_handoff_enabled=handoff.checked;
 return settings;
};
renderCustomerCareSection=function(){
 const template=document.createElement('template');template.innerHTML=careOriginalRender();
 const root=template.content,form=root.querySelector('#careForm');
 const settings=workspace.customer_care_settings||{},p=settings.dashboard_preferences||{};
 const toggle=(key,title,description,badge='',threshold='')=>`<div class="care-option"><label><span><strong>${title}</strong>${badge?`<em class="care-badge badge-${badge.toLowerCase()}">${badge}</em>`:''}<small>${description}</small></span><input type="checkbox" role="switch" data-care-setting="${key}" ${p[key]??(key==='order_tracking'?settings.order_tracking_enabled:key==='explicit_agent'?settings.human_handoff_enabled:true)?'checked':''}><i aria-hidden="true"></i></label>${threshold?`<div class="care-threshold"><label>Escalate after <input type="number" min="1" max="20" data-care-setting="${threshold}" value="${Number(p[threshold])||3}"> failed checks</label></div>`:''}</div>`;
 const section=(title,description,content)=>`<section class="care-design-section"><h3>${title}</h3><p class="care-description">${description}</p><div class="care-section-inner">${content}</div></section>`;
 const rules=section('1. Support configuration','Choose the categories your support assistant handles.',`<div class="care-options-grid">${toggle('order_tracking','Order tracking','Track orders and delivery estimates')}${toggle('delivery','Delivery status','Live tracking and delay notifications')}${toggle('returns','Returns & exchanges','Returns, swaps and refunds')}${toggle('policies','FAQs & policies','Store policies, sizing, payment info')}</div>`)
 +section('2. Human handoff & escalation','Define the conditions for recommending a live agent.',`<div class="care-escalations">${toggle('explicit_agent','Customer requests an agent','Escalate when the customer asks to speak to a human','Explicit')}${toggle('unresolved','Unresolved after attempts',"Repeated failures to resolve the customer's issue",'Threshold','unresolved_attempts')}${toggle('verification','Verification fails','Customer fails identity or order verification checks','Security','verification_attempts')}${toggle('frustrated','Frustrated or angry tone','Frustration, anger, or distress','AI')}${toggle('high_value','High-value request','Return or refund exceeds the order value threshold','Threshold')}${toggle('legal','Legal or compliance mention','Legal action, privacy requests, or formal complaints','Keyword')}</div>`)
 +section('3. Conversation context transfer','Choose the context to include when handing a conversation to your team.',`<p class="care-subheading">Core context</p><div class="care-options-grid care-core">${[['Full chat history','Complete conversation transcript'],['Customer information','Name, email, contact details'],['Order details','Order IDs, items, status']].map(([title,desc])=>`<div class="care-option"><strong>${title}</strong><small>${desc}</small></div>`).join('')}</div><p class="care-subheading">Optional <span>— Include when relevant to the conversation.</span></p><div class="care-options-grid">${toggle('context_intent','Customer intent','Detected goal and topic')}${toggle('context_actions','Previous bot actions','Steps already taken by the bot')}${toggle('context_verification','Verification status','What was verified and when')}</div>`)
 +section('4. Agent availability & response expectations','Set working hours and response time expectations.',`<label class="care-subheading">Working days</label><div class="care-days">${['Mon','Tue','Wed','Thu','Fri','Sat','Sun'].map(day=>`<label><input type="checkbox" data-care-day value="${day}" ${(p.working_days||['Mon','Tue','Wed','Thu','Fri']).includes(day)?'checked':''}><span>${day}</span></label>`).join('')}</div><label class="care-subheading">Working hours</label><div class="care-hours"><input type="time" aria-label="Start time" data-care-setting="start_time" value="${escapeHtml(p.start_time||'09:00')}"><span>to</span><input type="time" aria-label="End time" data-care-setting="end_time" value="${escapeHtml(p.end_time||'18:00')}"></div><div class="care-options-grid care-selects"><label>Time zone<select data-care-setting="timezone">${[...new Set([p.timezone||'Asia/Kolkata','Europe/Berlin','Europe/London','America/New_York','UTC'])].map(v=>`<option>${escapeHtml(v)}</option>`).join('')}</select></label><label>Est. resolution time<select data-care-setting="response_time">${[...new Set([p.response_time||'Within 24 hours','Within 2 hours','Within 48 hours','Next working day'])].map(v=>`<option>${escapeHtml(v)}</option>`).join('')}</select></label></div><label class="care-subheading" for="careAfterHours">After-hours message</label><textarea id="careAfterHours" data-care-setting="after_hours" rows="2">${escapeHtml(p.after_hours||"Our team is offline right now. We'll respond on the next working day.")}</textarea>`);
 const oldRules=Array.from(form.querySelectorAll('[data-care-pane="rules"]'));
 const details=document.createElement('details');details.className='care-existing';details.dataset.carePane='rules';details.innerHTML='<summary>Support contacts & existing handoff settings</summary>';oldRules.forEach(node=>{delete node.dataset.carePane;details.appendChild(node);});
 const rulesPane=document.createElement('div');rulesPane.dataset.carePane='rules';rulesPane.innerHTML=rules;form.prepend(rulesPane);rulesPane.appendChild(details);
 const knowledge=form.querySelector('[data-care-pane="knowledge"]');
 const data=workspace.overview;
 const stats=(items)=>`<div class="care-stat-grid">${items.map(([value,label])=>`<article><strong>${escapeHtml(String(value))}</strong><span>${label}</span></article>`).join('')}</div>`;
 knowledge.insertAdjacentHTML('afterbegin',section('1. Knowledge sources','Manage content for customer questions.',`<div class="care-options-grid">${[['faqs','FAQs'],['shipping','Shipping policies'],['sizing','Size charts'],['products','Product information'],['returns_source','Returns & exchanges'],['store_policies','Store policies']].map(([key,label])=>toggle('source_'+key,label,key==='faqs'?`${workspace.customer_care.length} saved answers`:'Manage through your knowledge base')).join('')}</div><div class="care-source-actions"><button type="button" class="secondary-button" disabled title="Document ingestion is not connected">Upload document</button><button type="button" class="secondary-button" data-care-write>Write manually</button><button type="button" class="secondary-button" disabled title="URL ingestion is not connected">Import URL</button></div>`)
 +section('2. Live sync settings','Keep support information aligned with your saved policies and FAQs.',`<div class="care-option care-sync"><strong>Saved knowledge</strong><small>FAQ updates are saved through Customer Care Setup. Automatic external-source sync is not connected.</small></div>`)
 +section('3. Knowledge coverage & issues','Review the available support knowledge.',stats([[workspace.customer_care.length,'Saved FAQ answers'],[workspace.knowledge_base.length,'Knowledge entries'],['—','Unresolved conversations']])+`<p class="care-subheading">Issues & fixes</p><div class="care-issue"><strong>${workspace.customer_care.length?'Review your support answers':'Add your first support answer'}</strong><p>Coverage and recurring-issue analytics are not yet recorded. Keep delivery and return policies up to date.</p><button type="button" class="primary-button" data-care-write>Add content</button></div>`)
 +section('4. Key metrics','Available activity from your connected store.',stats([[data.overview.support_questions_answered||0,'Support questions answered'],['—','Customer satisfaction'],['—','Escalation rate'],['—','Avg. resolution time'],['—','Resolution rate']])));
 const tabs=root.querySelectorAll('[data-care-tab]');tabs[1].textContent='Knowledge & Performance';
 const heading=root.querySelector('.workspace-card>.card-header');if(heading)heading.remove();
 form.classList.add('care-reference-form');
 return template.innerHTML;
};
mainContent.addEventListener('click',event=>{
 if(!event.target.closest('[data-care-write]'))return;
 const form=document.getElementById('careForm');const list=form.querySelector('.care-item');
 if(list){list.scrollIntoView({behavior:'smooth',block:'center'});list.querySelector('input[name="question"]')?.focus();}
});
sectionMeta.care.subtitle='Configure how your chatbot handles support requests, escalations, and live agent transfers';
