const trainingTabsBase = renderKnowledgeSection;
const trainingSignals = [['color','Color preferences',"Customer's preferred and avoided colors"],['style','Style signals','Minimalist, bold, classic — detected over time'],['budget','Budget range','Typical spend patterns across sessions'],['occasion','Shopping occasions','Work, evening, travel, everyday context'],['rejected','Rejected recommendations','Items the customer skipped or dismissed'],['patterns','Past interaction patterns','Frequency, session length, engagement depth']];
const trainingKeywords = [['Legal & Compliance',['Lawsuit','Legal Action','GDPR','Solicitor','Negligence','Attorney','Sue']],['Disputes & Fraud',['Dispute','Chargeback','Fraud','Scam','Stolen','Unauthorized','Claim','False Advertising']],['Escalation Signals',['Manager','Complaint','Unacceptable','Disgusting','Terrible','Worst','Never Again','Legal Supervisor']],['Sensitive Topics',['Harassment','Threatening','Abusive','Offensive','Discrimination','Inappropriate']]];
let trainingDraft = {signals:{occasion:true},keywords:['Lawsuit','Attorney','Court','Scam']};
let trainingDraftLoaded = false;
function trainingStorageKey(){return 'styledgenie:learning-draft:'+String(workspace.profile?.shop_domain||workspace.profile?.brand_name||'workspace');}
function loadTrainingDraft(){if(trainingDraftLoaded)return;trainingDraftLoaded=true;try{const saved=JSON.parse(localStorage.getItem(trainingStorageKey()));if(saved && Array.isArray(saved.keywords) && saved.signals && typeof saved.signals==='object')trainingDraft={signals:saved.signals,keywords:saved.keywords.filter(x=>typeof x==='string'&&x.length<=100)};}catch{}}
function saveTrainingDraft(){try{localStorage.setItem(trainingStorageKey(),JSON.stringify(trainingDraft));}catch{}}
const trainingIntro=(title,description)=>`<h3 class="training-title">${title}</h3><p class="training-description">${description}</p>`;
const trainingMeter=(value,label)=>`<progress max="100" value="${value}" aria-label="${escapeHtml(label)}">${value}%</progress>`;
function trainingRanking(title,rows){return `<article class="training-list"><h4>${title}</h4><ol>${rows.map(([label,count,badge,tone])=>`<li><span>${escapeHtml(label)}</span>${badge?`<b class="training-badge ${tone}">${badge}</b>`:''}<small>${count}&times;</small></li>`).join('')}</ol></article>`;}
function renderTrainingInsights(){
 const description='Aggregated patterns from customer conversations — what they ask, follow up on, and where they push back.';
 return `<section class="training-insights">${trainingIntro('Conversation Breakdown',description)}<div class="catalog-summary-grid">${[['Customer care',38,334],['Product discovery',29,255],['Styling help',21,185],['Complete the look',12,106]].map(([label,percent,count])=>`<article class="catalog-summary"><h3>${label}</h3><strong>${percent}%</strong><p>${count} conversations</p>${trainingMeter(percent,label)}</article>`).join('')}</div>${trainingIntro('Conversation Insights',description)}<div class="training-list-grid">${trainingRanking('Most Frequently Asked',[[ 'Do You Offer Free Shipping?',214],['What Is Your Return Policy?',182],['Can I Change Or Cancel My Order?',143],['How Long Does Delivery Take?',127],['Do You Have A Size Guide?',98]])}${trainingRanking('Common Follow-Up Questions',[[ 'After Return Policy → "What About Sale Items?"',89],['After Size Guide → "Which Size For Petite Frames?"',64],['After Shipping Info → "Can I Track My Order?"',57],['After Product Rec → "Does It Come In Other Colors?"',48],['After Payment → "Is There A Payment Plan?"',31]])}${trainingRanking('Repeated Objections & Clarifications',[[ '"That’s Not What I Meant"',44,'Misunderstood','red'],['"Can I Speak To A Person?"',30,'Escalation','yellow'],['"You Already Told Me That"',27,'Repetition','yellow'],['"That’s Not In My Budget"',20,'Budget','purple'],['"That’s Not In My Size"',15,'Size','purple']])}</div></section>`;
}
function renderTrainingPreferences(){
 const values=[82,71,58,50,44];
 const panels=[['Preferred Colors',['Black','Cream / Ivory','Navy','Camel / Tan','Olive / Sage'],['#000000','#f4f1e8','#203e64','#c29a68','#8e9e60']],['Style Preferences',['Minimalist','Classic / Timeless','Smart Casual','Workwear','Streetwear / Bold']],['Budget Tendencies',['Under $50','$50 – $150','$150 – $300','$300–$500','$500+']],['Shopping Occasions',['Everyday Wear','Work & Office','Evening & Events','Travel','Occasion Dressing']]];
 return `<section class="training-preferences">${trainingIntro('Customer Preferences & Style Signals','Aggregated signals the AI has learned from customer interactions. No individual data is exposed.')}<article class="training-acceptance"><h4>Recommendation Acceptance</h4><strong>71%</strong><p>Of AI Recommendations<br>Were Accepted</p>${trainingMeter(71,'Recommendation acceptance')}<footer><span>71% Accepted</span><span>29% Skipped</span></footer></article><div class="training-preference-grid">${panels.map(([title,labels,colors])=>`<article class="training-list"><h4>${title}</h4>${labels.map((label,i)=>`<div class="training-preference-row">${colors?`<i style="background:${colors[i]}" aria-hidden="true"></i>`:''}<span>${escapeHtml(label)}</span>${trainingMeter(values[i],label)}<small>${values[i]}%</small></div>`).join('')}</article>`).join('')}</div></section>`;
}
function renderTrainingControls(){loadTrainingDraft();return `<section class="training-controls"><p class="reference-data-note">Local preview settings saved in this browser. These controls are not connected to AI learning yet.</p>${trainingIntro('1. AI LEARNING SIGNALS','Choose which customer signals influence how the AI learns and personalises future recommendations.<br>Disabling a signal means the AI will ignore that dimension entirely.')}<div class="training-signal-grid">${trainingSignals.map(([key,title,description])=>`<label class="training-signal"><span>${title}<small>${escapeHtml(description)}</small></span><input type="checkbox" role="switch" data-training-signal="${key}" ${trainingDraft.signals[key]?'checked':''}><i aria-hidden="true"></i></label>`).join('')}</div>${trainingIntro('2. SENSITIVE WORDS & WORKFLOW','When these words appear in a conversation, the AI will not learn from that session. Use this to protect sensitive interactions like disputes, complaints, legal language from influencing AI behaviour.')}<form id="trainingKeywordForm"><label class="catalog-sr-only" for="trainingKeywordInput">Sensitive word or phrase</label><input id="trainingKeywordInput" maxlength="100" required placeholder="Type a phrase/word..."><button class="primary-button" type="submit">Add</button></form><h4>Active Keywords</h4><div class="training-active-keywords">${trainingDraft.keywords.map((word,index)=>`<button type="button" data-training-remove="${index}" aria-label="Remove ${escapeHtml(word)}">${escapeHtml(word)} <span aria-hidden="true">&times;</span></button>`).join('')||'<span>No active keywords</span>'}</div><article class="training-suggestions"><header><span aria-hidden="true">&#10023;</span> AI Suggested Keywords — Click Any To Add <small>Sample suggestions</small></header>${trainingKeywords.map(([title,words])=>`<section><h4>${title}</h4><div>${words.map(word=>`<button type="button" data-training-add="${escapeHtml(word)}" ${trainingDraft.keywords.some(x=>x.toLowerCase()===word.toLowerCase())?'disabled':''}>${word} <span aria-hidden="true">+</span></button>`).join('')}</div></section>`).join('')}</article><details class="training-editor"><summary>Knowledge content editor</summary>${previousScreens.knowledge()}</details></section>`;}
renderKnowledgeSection = function(){
 const tab=screenState.knowledge;if(!['insights','preferences','controls'].includes(tab))return trainingTabsBase();
 const tabs=screenTabs('knowledge',[['knowledge','Knowledge gaps'],['insights','Conversation Insights'],['preferences','Customer Preferences'],['controls','Learning & Controls']],tab);
 if(tab==='controls')return tabs+renderTrainingControls();
 if(!knowledgeReferenceDemo)return tabs+dashboardSampleNote('knowledge',false)+(tab==='insights'?renderServiceMix(workspace.overview)+renderActivityFeed(workspace.overview):'<p class="card-copy">Customer preference reporting is not yet available in the workspace data.</p>');
 return tabs+dashboardSampleNote('knowledge',true)+(tab==='insights'?renderTrainingInsights():renderTrainingPreferences());
};
function addTrainingKeyword(word){word=word.trim().slice(0,100);if(!word||trainingDraft.keywords.some(x=>x.toLowerCase()===word.toLowerCase()))return;trainingDraft.keywords.push(word);saveTrainingDraft();}
mainContent.addEventListener('change',event=>{if(event.target.matches('[data-training-signal]')){trainingDraft.signals[event.target.dataset.trainingSignal]=event.target.checked;saveTrainingDraft();}});
mainContent.addEventListener('submit',event=>{if(event.target.id!=='trainingKeywordForm')return;event.preventDefault();addTrainingKeyword(event.target.querySelector('input').value);renderSection();mainContent.querySelector('#trainingKeywordInput')?.focus();});
mainContent.addEventListener('click',event=>{const add=event.target.closest('[data-training-add]'),remove=event.target.closest('[data-training-remove]');if(add){addTrainingKeyword(add.dataset.trainingAdd);renderSection();}if(remove){trainingDraft.keywords.splice(Number(remove.dataset.trainingRemove),1);saveTrainingDraft();renderSection();mainContent.querySelector('#trainingKeywordInput')?.focus();}if(event.target.closest('[data-gap-add]')){const editor=mainContent.querySelector('.training-editor');if(editor){editor.open=true;editor.scrollIntoView({behavior:'smooth',block:'start'});editor.querySelector('input')?.focus();}}});
